[Unit]
After=sys-subsystem-net-devices-wlan0.device
Before=wpa_supplicant@wlan0.service

[Service]
ExecStartPre=/bin/sh -c '/sbin/rfkill unblock wifi; /sbin/ip link set dev wlan0 up'

[Install]
WantedBy=multi-user.target
